name: CI/CD Pipelines

on:
  push:
    branches:
      - main

jobs:
  backend-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./backend-api
      - name: Run Test
        run: npm test
        working-directory: ./backend-api 
      
      - name: Build Docker Image for Backend
        run: |
          docker build -t sirwills/backend-api:latest -f ./backend-api/Dockerfile ./backend-api

      - name: Push Docker Image for Backend
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push sirwills/backend-api:latest


  frontend-webapp-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend-webapp/webapp
      - name: Run build
        run: npm run build
        working-directory: ./frontend-webapp/webapp
      
      - name: Build Docker Image for Backend
        run: |
          docker build -t sirwills/backend-api:latest -f ./backend-api/Dockerfile ./backend-api

              
      - name: Push Docker Image for Backend
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push sirwills/backend-api:latest


